config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"

  # login
  get "users/new"
  get "users/register"
  post 'users/sign_in'
  post 'users/sign_up'
  delete 'users/logout'

  # post
  get '/posts', to: "posts#index", format: "json"
  post "/post/create", to: "posts#create", format: "json"

  # comment
  post "/comment/create/:post_id", to: "comments#create", format: "json"

  #likes
  post "/like/:post_id", to: "likes#create"
  delete "/like/:post_id", to: "likes#destroy"

  # profile
  get "/profile", to: "profiles#index"
  get "/profile/:id", to: "profiles#show"

  # google
  get '/auth/google_oauth2/callback', to: 'users#omniauth'

  # search
  get '/search/:search_id', to: 'search#index'
  post '/search/:search_id', to: 'search#search_results'

  # history
  get "/histories", to: "history#index", format: "json"
  post "/history", to: "history#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#  like       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  description :text
#  user_id     :bigint
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id         :bigint           not null, primary key
#  results    :jsonb            is an Array
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Search < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :bigint           not null, primary key
#  email                :string           not null
#  name                 :string           not null
#  password_digest      :string           not null
#  uid                  :string
#  google_token         :string
#  google_refresh_token :string
#  image                :string
#  search_id            :bigint
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class User < ApplicationRecord
  has_many :posts
  has_many :histories
  belongs_to :search

  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }

  def self.from_omniauth(auth)
    #Creates a new user only if it doesn't exist
    where(email: auth.info.email).first_or_initialize do |user|
      user.user_name = auth.info.name
      user.email = auth.info.email
      if auth.info.uid
        user.uid = auth.info.uid
      end
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  include UsersHelper
  before_action :current_user

  def authenticate_user!
    if Current.user.nil?
      redirect_to users_new_path
    end
  end

  def current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def check_user
    if Current.user.present?
      redirect_to "/"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(content: params[:content], user_id: Current.user.id, post_id: params[:post_id])

    if comment.save
      @comments = Post.find(params[:post_id]).comments
    end
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @histories = History.all
  end

  def create
    image_history = params[:history][:url_image]
    video_history = params[:history][:url_video]
    history = History.find_by(user_id: Current.user.id)

    if history.nil?
      History.create(user_id: Current.user.id, image: [image_history], video: [video_history])
      render json: "Congratulations, your story was created, and an email was sent to you, check it out!!"
    else
      history.update(image: history.image << image_history) if image_history.present?
      history.update(video: history.video << video_history) if video_history.present?
      render json: "Congratulations, your story was updated, and an email was sent to you, check it out!!"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = Current.user
    @posts = Post.all
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(user_id: Current.user.id, post_id: params[:post_id])

    if @like.save
      render json: Post.find(params[:post_id]).likes
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])

    if @post.present?
      @like_post = @post.likes.find_by(user_id: Current.user.id)

      if @like_post.present?
        @like_post.destroy
        render json: Post.find(params[:post_id]).likes
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(description: params[:description], image: params[:image], user_id: Current.user.id)

    if @post.save
      @posts = Current.user.posts.order("created_at DESC")
    end
  end

  def index
    @posts = Post.all.order("created_at DESC")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    new_res = {}
    @user = Current.user
    @post = @user.posts.find_by(id: params[:post])

    render json: { user: @user, posts: @user.posts }
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search = Search.find(params[:search_id])
    render json: search.results
  end

  def search_results
    search = Search.find(params[:search_id])

    render json: "Search ID is in valid"  if !search.valid?

    users = User.find_by("name ILIKE ?", "%#{params[:text]}%") if !params[:text].nil?

    if search.results.include?(users.as_json) == false && !users.nil?
      search.update(results: search.results << users)
      render json: search.results
    else
      render json: search.results
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, except: [:logout]

  def new
    @user = User.new
  end

  def register
  end

  def sign_in
    @user = User.find_by(email: params_user[:email])

    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      redirect_to '/'
    end
  end

  def sign_up
    @search = Search.create
    @user = User.new(params_user.merge(search_id: @search.id))

    if @user.save
      session[:user_id] = @user.id

      redirect_to "/"
    end
  end


  def logout
    session[:user_id] = nil

    render json: "Logout"
  end

  def omniauth
    @user = User.find_or_create_by(uid: auth['uid']) do |user|
      user.name = auth['info']['name']
      user.email = auth['info']['email']
      user.image = auth['info']['image']
      access_token = auth
      user.google_token = auth.credentials.token
      refresh_token = auth.credentials.refresh_token
      user.google_refresh_token = refresh_token if refresh_token.present?
      user.password = SecureRandom.urlsafe_base64
      user.search_id = Search.create.id
    end
    log_in @user
    redirect_to "/"
  end

  def auth
    request.env['omniauth.auth']
  end

  private

  def params_user
    params.permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cookie&family=League+Spartan:wght@300&family=Pacifico&family=Rubik:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= favicon_link_tag 'logo.svg' %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'home', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_all_post.html.erb
<section class="mt-10 m-auto container-posts">
  <% @posts.order("created_at DESC").map do |post| %>
  <div class="border-solid border-2 border-gray-100 p-2 m-auto mt-10 mb-10">
    <div class="flex items-center mb-4">
      <span
        class="py-1 px-3 rounded-full mr-4 bg-purple-300 flex justify-center items-center"
      >
        <%= User.find(post.user_id).name.slice(0, 1) %>
      </span>
      <%= User.find(post.user_id).name %>
    </div>

    <div class="w-full"><%= image_tag post.image.url, class: "m-auto" %></div>

    <div class="mt-4">
      <div class="flex items-center gap-3 mb-2">
        <% if post.likes.find_by(user_id: Current.user.id) %>
          <%= button_to "❤️", "/like/#{post.id}", method: :delete, class: "cursor-pointer" %>
          <% else %>
          <%= button_to "♡", "/like/#{post.id}", method: :post, class: "cursor-pointer" %>
        <% end %>
        <%= tag.span "#{post.likes.length} likes",  id: "like", class: "text-sm font-bold" %>
      </div>
      <%= User.find(post.user_id).name %> <%= tag.strong post.description %>
    </div>

    <div class="mt-4">
      <% post.comments.order('created_at DESC').map do |item| %>
      <div class="flex items-center justify-between">
        <p>
          <%= tag.strong User.find(item.user_id).name %> <%= item.content %>
        </p>
        <%= tag.span Date.parse(item.created_at.to_s), class: "text-sm" %>
      </div>
      <% end %>
      <strong class="block mt-4">
        <%= "#{post.comments.length} comments" %>
      </strong>
    </div>

    <div>
      <%= form_with locale: true, url: "/comment/create/#{post.id}" do |form| %>
      <%= form.text_field :content, class: "mt-4 p-2 bg-gray-50 w-full rounded-sm border-0.5 border-solid border-blue-50", placeholder: "Content..." %>
      <%= form.button "Create comment", class: "mt-4 bg-blue-200 p-1 rounded text-sm cursor-pointer font-bold" %> <% end %>
    </div>
  </div>
  <% end %>
</section>

app/views/partials/_form_post.html.erb
<%= form_with  url: post_create_path, locale: true, class: "bg-white p-4 w-3/6 m-auto flex justify-center flex-col relative" do |form| %>
  <p onclick="document.getElementById('post-modal').style.display = 'none'" class="absolute right-5 top-4 cursor-pointer">X</p>
  <strong class="cursor-pointer mb-5 flex items-center">
    <span class="py-1 px-3 rounded-full mr-4 bg-purple-300 flex justify-center items-center">
      <%=  @user.name.slice(0, 1) %>
    </span>
    <%= @user.name %>
  </strong>

  <%= form.text_field :description, placeholder: "Description ..." %>

  <div class="mt-10">
    <%= form.file_field :image %>
  </div>

  <%= form.button "Create post", onclick: "document.getElementById('post-modal').style.display = 'none'", class: "p-2 bg-blue-500 mt-5 text-white" %>
<% end %>

app/views/partials/_nav.html.erb
<div
  class="p-2 bg-white shadow-md items-center sm:flex md:justify-around justify-between"
>
  <h1 class="font-bold text-4xl home-h1 sm:m-auto mb-4">Instagram</h1>

  <%# Search %>
  <div class="relative">
    <%= form_with locale: true, url: "/search/#{@user.search.id}" do |form| %>
      <%= form.text_field :text, placeholder: "🔍 Search", class: "p-1 bg-gray-100 outline-none rounded-md w-80 m-auto block", onclick: "document.getElementById('results').style.display = 'block'" %>
    <% end %>

    <div class="hidden absolute bg-white shadow-lg w-80 mt-4 p-2 box-content" id="results">
      <p class="flex items-center justify-between font-bold mb-4" onclick="document.getElementById('results').style.display = 'none'">Results <strong class="font-bold cursor-pointer">X</strong></p>
      <%= tag.strong "Not results", class: "text-center block" if @user.search.results.length === 0 %>
      <% @user.search.results.map do |item| %>
      <div class="flex items-center gap-4 mt-4">
        <% if item["image"].nil? %>
          <div class="bg-purple-300 px-3 rounded-full w-7 h-7 flex items-center justify-center">
            <strong class="cursor-pointer"> <%= item["name"].slice(0, 1) %> </strong>
          </div>
          <% else %>
          <%= image_tag item["image"], class: "rounded-full w-7 h-7" %>
        <% end %>
        <%= tag.strong item["name"] %>
      </div>
      <% end %>
      <%= link_to "Refresh results", "/", class: 'block mt-2 text-center bg-blue-200 p-1 rounded-sm' %>
    </div>
  </div>
  <%#  %>

  <div class="flex justify-center items-center sm:m-auto mt-4 relative">
    <a href="/" class="mr-4">
      <%= image_tag "https://icongr.am/octicons/home-fill.svg?size=30&color=currentColor", style: "cursor: pointer" %>
    </a>
    <div onclick="document.getElementById('post-modal').style.display = 'flex'">
      <%= image_tag "https://icongr.am/feather/plus-square.svg?size=30&color=currentColor", style: "cursor: pointer" %>
    </div>
    <div
      class="border-solid border-3 border-gray-400 py-1 px-4"
      onclick="document.getElementById('info').style.display === 'none' ? document.getElementById('info').style.display = 'block' : document.getElementById('info').style.display = 'none'"
    >
      <% if @user.image.nil? %>
        <div class="bg-purple-300 px-3">
          <strong class="cursor-pointer"> <%= @user.name.slice(0, 1) %> </strong>
        </div>
        <% else %>
          <%= image_tag @user.image, class: "rounded-full w-7 h-7" %>
        <% end %>
    </div>

    <div
      class="hidden absolute top-12 left-24 bg-white shadow-lg w-4/6 box-border text-center p-2"
      id="info"
    >
      <%= link_to "Profile", "/profile", class: "block" %>
      <div class="border-t-2 mt-4 border-gray-200 border-solid">
        <%= button_to "Logout", users_logout_path, method: :delete, class:
        "cursor-pointer" %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex justify-center gap-20 mt-20">
  <div class="relative lg:block hidden">
    <%= image_tag "https://www.instagram.com/static/images/homepage/phones/home-phones-2x.png/cbc7174b4f05.png", class: "image-login-general" %>
    <%= image_tag "https://www.instagram.com/static/images/homepage/screenshots/screenshot3-2x.png/fe2540684ab2.png", class: "image-login absolute top-4 left-32" %>
  </div>
  <div class="container-login">
    <div class="border-2 border-solid border-gray-100 p-10">
      <h1 class="font-bold text-4xl home-h1 sm:m-auto mb-4 text-center">
        Instagram
      </h1>
      <div class="mt-5">
        <%= form_with url: users_sign_in_path, local: true do |form| %>
          <%= form.text_field :email, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 outline-none", placeholder: "Email" %>
          <%= form.password_field :password, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 mt-5 outline-none", placeholder: "Password" %>
          <%= form.button "Log in", class: "bg-blue-400 p-2 rounded w-4/6 m-auto
          block mt-4 text-white font-bold" %>
        <% end %>
      </div>

      <p class="text-center mt-10">OR</p>
      <div class="mt-5 flex justify-center gap-2 items-center">
        <%= image_tag "https://icongr.am/devicon/google-original.svg?size=24&color=currentColor" %>
        <%= button_to "Sign in with Google", '/auth/google_oauth2', method: :get, class: "cursor-pointer" %>
      </div>
    </div>
    <div
      class="border-2 border-solid border-gray-100 p-5 text-sm mt-10 text-center"
    >
      <strong>
        Don't have an account? <%= link_to "Sign up", users_register_path, class:
        "text-blue-400" %>
      </strong>
    </div>
  </div>
</div>

app/views/users/register.html.erb
<div class="flex justify-center gap-20 mt-20">
  <div class="relative lg:block hidden">
    <%= image_tag "https://www.instagram.com/static/images/homepage/phones/home-phones-2x.png/cbc7174b4f05.png", class: "image-login-general" %>
    <%= image_tag "https://www.instagram.com/static/images/homepage/screenshots/screenshot3-2x.png/fe2540684ab2.png", class: "image-login absolute top-4 left-32" %>
  </div>
  <div class="container-login">
    <div class="border-2 border-solid border-gray-100 p-10">
      <h1 class="font-bold text-4xl home-h1 sm:m-auto mb-4 text-center">
        Instagram
      </h1>
      <div class="mt-5">
        <%= form_with url: users_sign_up_path, local: true do |form| %>
          <%= form.text_field :name, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 outline-none mb-5 text-sm", placeholder: "Name" %>
          <%= form.text_field :email, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 outline-none text-sm", placeholder: "Email" %>
          <%= form.password_field :password, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 mt-5 outline-none text-sm", placeholder: "Password" %>
          <%= form.password_field :password_confirmation, class: "bg-gray-100 w-4/6 m-auto block rounded-md p-1.5 mt-5 outline-none text-sm", placeholder: "Password confirmation" %>
          <%= form.button "Sign up", class: "bg-blue-400 p-2 rounded w-4/6 m-auto block mt-4 text-white font-bold" %>
        <% end %>
      </div>
      <p class="text-center mt-5">OR</p>
      <div class="mt-5 flex justify-center gap-2 items-center">
        <%= image_tag "https://icongr.am/devicon/google-original.svg?size=24&color=currentColor" %>
        <%= button_to "Sing up with Google", '/auth/google_oauth2', method: :get, class: "cursor-pointer" %>
      </div>
    </div>
    <div
      class="border-2 border-solid border-gray-100 p-5 text-sm mt-10 text-center"
    >
      <strong>
        Do you have an account? <%= link_to "Sign in", users_new_path, class:
        "text-blue-400" %>
      </strong>
    </div>
  </div>
</div>